# Generated by Django 5.0 on 2023-12-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='max_capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
