# Generated by Django 5.0 on 2023-12-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('owner', 'Owner'), ('customer', 'Customer')], default='customer', max_length=32),
        ),
    ]
